version: "3"
services:
  file-watcher:
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
        UNAME: xyon
    user: xyon
    restart: "always"
    expose:
      - "8081"
    ports:
      - "3000:8081"
    volumes:
      - ./server:/app
    command:
      - /bin/bash
      - -c
      - |
        export PATH=/home/xyon/.deno/bin:$PATH
        cd /app
        chmod u+x start.sh
        ./start.sh
